package de.unibielefeld.gi.kotte.laborprogramm.spotTableExporter;

import javax.swing.JPanel;

/**
 * Wizard Panel for the Spot Data Export Options.
 *
 * @author kotte
 */
public final class ExportOptionsVisualPanel1 extends JPanel {

    public static final String PROPERTY_SPOT_GROUP_ID = "spot groud id";
    public static final String PROPERTY_IDENTIFICATION_NAME = "identification name";

    public boolean isSpotGroupId() {
        return spotGroupIdBox.isSelected();
    }

    public boolean isIdentificationName() {
        return identificationNameBox.isSelected();
    }

    /** Creates new form ExportOptionsVisualPanel1 */
    public ExportOptionsVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Ausgabeoptionen fuer Spot Data Export";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        spotGroupIdBox = new javax.swing.JCheckBox();
        identificationNameBox = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(headingLabel, org.openide.util.NbBundle.getMessage(ExportOptionsVisualPanel1.class, "ExportOptionsVisualPanel1.headingLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(spotGroupIdBox, org.openide.util.NbBundle.getMessage(ExportOptionsVisualPanel1.class, "ExportOptionsVisualPanel1.spotGroupIdBox.text")); // NOI18N
        spotGroupIdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spotGroupIdBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(identificationNameBox, org.openide.util.NbBundle.getMessage(ExportOptionsVisualPanel1.class, "ExportOptionsVisualPanel1.identificationNameBox.text")); // NOI18N
        identificationNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificationNameBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificationNameBox)
                    .addComponent(spotGroupIdBox)
                    .addComponent(headingLabel))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spotGroupIdBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identificationNameBox)
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spotGroupIdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spotGroupIdBoxActionPerformed
        firePropertyChange(PROPERTY_SPOT_GROUP_ID, !spotGroupIdBox.isSelected(), spotGroupIdBox.isSelected());
    }//GEN-LAST:event_spotGroupIdBoxActionPerformed

    private void identificationNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificationNameBoxActionPerformed
        firePropertyChange(PROPERTY_IDENTIFICATION_NAME, !identificationNameBox.isSelected(), identificationNameBox.isSelected());
    }//GEN-LAST:event_identificationNameBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headingLabel;
    private javax.swing.JCheckBox identificationNameBox;
    private javax.swing.JCheckBox spotGroupIdBox;
    // End of variables declaration//GEN-END:variables
}
