/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.unibielefeld.gi.kotte.laborprogramm.wellIdentificationViewer;

import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.identification.IWellIdentification;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.plate384.IWell384;
import java.awt.BorderLayout;
import java.beans.IntrospectionException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Logger;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.explorer.propertysheet.PropertySheet;
import org.openide.nodes.BeanNode;
import org.openide.util.Exceptions;
import org.openide.util.Lookup.Result;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
dtd = "-//de.unibielefeld.gi.kotte.laborprogramm.wellIdentificationViewer//WellIdentificationViewer//EN",
autostore = false)
public final class WellIdentificationViewerTopComponent extends TopComponent
        implements LookupListener {

    private static WellIdentificationViewerTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "WellIdentificationViewerTopComponent";
    private PropertySheet ps;
    private Result<IWell384> result;

    public WellIdentificationViewerTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(WellIdentificationViewerTopComponent.class,
                "CTL_WellIdentificationViewerTopComponent"));
        setToolTipText(NbBundle.getMessage(
                WellIdentificationViewerTopComponent.class,
                "HINT_WellIdentificationViewerTopComponent"));
//        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
        ps = new PropertySheet();
        add(ps, BorderLayout.CENTER);
        result = Utilities.actionsGlobalContext().lookupResult(IWell384.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized WellIdentificationViewerTopComponent getDefault() {
        if (instance == null) {
            instance = new WellIdentificationViewerTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the WellIdentificationViewerTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized WellIdentificationViewerTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(
                PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(
                    WellIdentificationViewerTopComponent.class.getName()).
                    warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof WellIdentificationViewerTopComponent) {
            return (WellIdentificationViewerTopComponent) win;
        }
        Logger.getLogger(WellIdentificationViewerTopComponent.class.getName()).
                warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        result.addLookupListener(this);
    }

    @Override
    public void componentClosed() {
        result.removeLookupListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    @Override
    public void resultChanged(LookupEvent ev) {
        List<BeanNode> nodeList = new LinkedList<BeanNode>();
        for (IWell384 spot : result.allInstances()) {
            IWellIdentification ident = spot.getIdentification();
            if (ident != null && !ident.getIdentifications().isEmpty()) {
                try {
                    nodeList.add(new WellIdentificationNode(ident));
                } catch (IntrospectionException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
        }
        if (!nodeList.isEmpty()) {
            ps.setNodes(nodeList.toArray(new BeanNode[]{}));
        }
    }
}
