package de.unibielefeld.gi.kotte.laborprogramm.spotDetailViewer;

import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.ISpot;
import java.awt.BorderLayout;
import java.beans.IntrospectionException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Logger;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.explorer.propertysheet.PropertySheet;
import org.openide.nodes.BeanNode;
import org.openide.util.Exceptions;
import org.openide.util.Lookup.Result;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle;
import org.openide.util.Utilities;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
dtd = "-//de.unibielefeld.gi.kotte.laborprogramm.spotDetailViewer//SpotDetailViewer//EN",
autostore = false)
public final class SpotDetailViewerTopComponent extends TopComponent implements
        LookupListener {

    private static SpotDetailViewerTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "SpotDetailViewerTopComponent";
    private PropertySheet ps;
    private Result<ISpot> result;

    public SpotDetailViewerTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(SpotDetailViewerTopComponent.class,
                "CTL_SpotDetailViewerTopComponent"));
        setToolTipText(NbBundle.getMessage(SpotDetailViewerTopComponent.class,
                "HINT_SpotDetailViewerTopComponent"));
//        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
        ps = new PropertySheet();
        add(ps, BorderLayout.CENTER);
        result = Utilities.actionsGlobalContext().lookupResult(ISpot.class);
        resultChanged(new LookupEvent(result));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized SpotDetailViewerTopComponent getDefault() {
        if (instance == null) {
            instance = new SpotDetailViewerTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the SpotDetailViewerTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized SpotDetailViewerTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(
                PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(SpotDetailViewerTopComponent.class.getName()).
                    warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof SpotDetailViewerTopComponent) {
            return (SpotDetailViewerTopComponent) win;
        }
        Logger.getLogger(SpotDetailViewerTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        result.addLookupListener(this);
    }

    @Override
    public void componentClosed() {
        result.removeLookupListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    @Override
    public void resultChanged(LookupEvent ev) {
        List<BeanNode> nodeList = new LinkedList<BeanNode>();
        for (ISpot spot : result.allInstances()) {
            try {
                nodeList.add(new BeanNode(spot));
            } catch (IntrospectionException ex) {
                Exceptions.printStackTrace(ex);
            }
        }
        if (!nodeList.isEmpty()) {
            ps.setNodes(nodeList.toArray(new BeanNode[]{}));
        }
    }
}
