package de.unibielefeld.gi.kotte.laborprogramm.testModule;

import de.unibielefeld.gi.kotte.laborprogramm.ImportWizard.ImportWizardAction;
import de.unibielefeld.gi.kotte.laborprogramm.plateViewer.Plate384Panel;
import de.unibielefeld.gi.kotte.laborprogramm.plateViewer.Plate96Panel;
import de.unibielefeld.gi.kotte.laborprogramm.project.api.IProteomicProject;
import de.unibielefeld.gi.kotte.laborprogramm.project.api.IProteomicProjectFactory;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.IProject;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.IProjectFactory;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.IGel;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.IGelFactory;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.ISpot;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.ISpotFactory;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.SpotStatus;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.group.IBioRepGelGroup;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.group.IBioRepGelGroupFactory;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.group.ILogicalGelGroup;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.group.ILogicalGelGroupFactory;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.group.ISpotGroup;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.group.ISpotGroupFactory;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.group.ITechRepGelGroup;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.gel.group.ITechRepGelGroupFactory;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.plate384.IPlate384;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.plate384.IPlate384Factory;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.plate384.IWell384;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.plate384.Well384Status;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.plate96.IPlate96;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.plate96.IPlate96Factory;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.plate96.IWell96;
import de.unibielefeld.gi.kotte.laborprogramm.proteomik.api.plate96.Well96Status;
import java.io.File;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JPanel;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.Lookup;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//de.unibielefeld.gi.kotte.laborprogramm.testModule//TestModule//EN",
autostore = false)
public final class TestModuleTopComponent extends TopComponent {

    private static TestModuleTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "TestModuleTopComponent";

    public TestModuleTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(TestModuleTopComponent.class, "CTL_TestModuleTopComponent"));
        setToolTipText(NbBundle.getMessage(TestModuleTopComponent.class, "HINT_TestModuleTopComponent"));
//        setIcon(ImageUtilities.loadImage(ICON_PATH, true));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plate96TestButton = new javax.swing.JButton();
        plate384TestButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(plate96TestButton, org.openide.util.NbBundle.getMessage(TestModuleTopComponent.class, "TestModuleTopComponent.plate96TestButton.text")); // NOI18N
        plate96TestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plate96TestButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(plate384TestButton, org.openide.util.NbBundle.getMessage(TestModuleTopComponent.class, "TestModuleTopComponent.plate384TestButton.text")); // NOI18N
        plate384TestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plate384TestButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(TestModuleTopComponent.class, "TestModuleTopComponent.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(TestModuleTopComponent.class, "TestModuleTopComponent.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plate96TestButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plate384TestButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plate96TestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plate384TestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void plate96TestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plate96TestButtonActionPerformed
        IPlate96 plate = Lookup.getDefault().lookup(IPlate96Factory.class).createPlate96();
        JPanel panel = new Plate96Panel(plate);
        JDialog dialog = new JDialog();
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_plate96TestButtonActionPerformed

    private void plate384TestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plate384TestButtonActionPerformed
        IPlate384 plate = Lookup.getDefault().lookup(IPlate384Factory.class).createPlate384();
        JPanel panel = new Plate384Panel(plate);
        JDialog dialog = new JDialog();
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_plate384TestButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ImportWizardAction().performAction();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        IProject proj = createTestProject();

        //create project directory auto123...
        File projectDirectoryFile = new File("/homes/kotte/testDirectory/auto" + System.currentTimeMillis());
        projectDirectoryFile.mkdirs();
        
        IProteomicProjectFactory ippf = Lookup.getDefault().lookup(IProteomicProjectFactory.class);
        IProteomicProject pp = ippf.createProject(projectDirectoryFile,proj);
    }//GEN-LAST:event_jButton2ActionPerformed

     private IProject createTestProject() {
        IProject project = null;
        project = Lookup.getDefault().lookup(IProjectFactory.class).createEmptyProject();
        project.setName("Dummy Projekt");
        project.setDescription("Testprojekt zum testen der Proteomik API Datenstrukturen");
        project.setOwner("kotte");

        //set up logical gel group
        ILogicalGelGroup logical = Lookup.getDefault().lookup(ILogicalGelGroupFactory.class).createLogicalGelGroup();
        logical.setName("Testgruppe high level");
        logical.setDescription("Mock Objekt zum Test der Datenstruktur");
        logical.setParent(project);
        project.addGelGroup(logical);

        //set up two bio rep gel groups
        IBioRepGelGroup biorep1 = Lookup.getDefault().lookup(IBioRepGelGroupFactory.class).createBioRepGelGroup();
        biorep1.setName("Testgruppe #1 mid level");
        biorep1.setDescription("Mock Objekt zum Test der Datenstruktur");
        biorep1.setParent(logical);
        logical.addGelGroup(biorep1);
        IBioRepGelGroup biorep2 = Lookup.getDefault().lookup(IBioRepGelGroupFactory.class).createBioRepGelGroup();
        biorep2.setName("Testgruppe #2 mid level");
        biorep2.setDescription("Mock Objekt zum Test der Datenstruktur");
        biorep2.setParent(logical);
        logical.addGelGroup(biorep2);

        //set up two tech rep gel groups (one for each bio rep gel group)
        ITechRepGelGroup techrep1 = Lookup.getDefault().lookup(ITechRepGelGroupFactory.class).createTechRepGelGroup();
        techrep1.setName("Testgruppe #1 low level");
        techrep1.setDescription("Mock Objekt zum Test der Datenstruktur");
        techrep1.setParent(biorep1);
        biorep1.addGelGroup(techrep1);
        ITechRepGelGroup techrep2 = Lookup.getDefault().lookup(ITechRepGelGroupFactory.class).createTechRepGelGroup();
        techrep2.setName("Testgruppe #2 low level");
        techrep2.setDescription("Mock Objekt zum Test der Datenstruktur");
        techrep2.setParent(biorep2);
        biorep2.addGelGroup(techrep2);

        //set up two gels (one for each tech rep gel group)
        IGel gel1 = Lookup.getDefault().lookup(IGelFactory.class).createGel();
        gel1.setDescription("Mock Objekt zum Test der Datenstruktur");
        gel1.setName("Testgel #1");
        gel1.setParent(techrep1);
        techrep1.addGel(gel1);
        IGel gel2 = Lookup.getDefault().lookup(IGelFactory.class).createGel();
        gel2.setDescription("Mock Objekt zum Test der Datenstruktur");
        gel2.setName("Testgel #2");
        gel2.setParent(techrep2);
        techrep2.addGel(gel2);

        //set up some spots for the two gels
        ISpot spot11 = Lookup.getDefault().lookup(ISpotFactory.class).createSpot();
        spot11.setNumber(1);
        spot11.setPosX(100);
        spot11.setPosY(199);
        spot11.setLabel("Spot #1 on gel #1");
        spot11.setGel(gel1);
        gel1.addSpot(spot11);
        ISpot spot12 = Lookup.getDefault().lookup(ISpotFactory.class).createSpot();
        spot12.setNumber(2);
        spot12.setPosX(200);
        spot12.setPosY(100);
        spot12.setLabel("Spot #2 on gel #1");
        spot12.setGel(gel1);
        gel1.addSpot(spot12);
        ISpot spot21 = Lookup.getDefault().lookup(ISpotFactory.class).createSpot();
        spot21.setNumber(1);
        spot21.setPosX(99);
        spot21.setPosY(200);
        spot21.setLabel("Spot #1 on gel #2");
        spot21.setGel(gel2);
        gel2.addSpot(spot21);
        ISpot spot22 = Lookup.getDefault().lookup(ISpotFactory.class).createSpot();
        spot22.setNumber(2);
        spot22.setPosX(199);
        spot22.setPosY(99);
        spot22.setLabel("Spot #2 on gel #2");
        spot22.setGel(gel1);
        gel2.addSpot(spot22);

        //set up groups of spots
        ISpotGroup spotgroup1 = Lookup.getDefault().lookup(ISpotGroupFactory.class).createSpotGroup();
        spotgroup1.setLabel("Spot #1");
        spotgroup1.setNumber(1);
        spotgroup1.addSpot(spot11);
        spot11.setGroup(spotgroup1);
        spotgroup1.addSpot(spot21);
        spot21.setGroup(spotgroup1);
        project.addSpotGroup(spotgroup1);
        ISpotGroup spotgroup2 = Lookup.getDefault().lookup(ISpotGroupFactory.class).createSpotGroup();
        spotgroup2.setLabel("Spot #2");
        spotgroup2.setNumber(2);
        spotgroup2.addSpot(spot12);
        spot12.setGroup(spotgroup2);
        spotgroup2.addSpot(spot22);
        spot22.setGroup(spotgroup2);
        project.addSpotGroup(spotgroup2);

        //set up a 96 well microplate
        IPlate96 plate96 = Lookup.getDefault().lookup(IPlate96Factory.class).createPlate96();
        plate96.setName("Testplatte");
        plate96.setDescription("Mock Objekt zum Test der Datenstruktur");
        plate96.setParent(project);
        project.add96Plate(plate96);

        //collect some wells for our spots from the plates
        IWell96 wellA1 = plate96.getWell('A', 1);
        IWell96 wellA2 = plate96.getWell('A', 2);
        IWell96 wellB1 = plate96.getWell('B', 1);
        IWell96 wellB2 = plate96.getWell('B', 2);

        //provide picking information
        wellA1.setSpot(spot11);
        wellA1.setStatus(Well96Status.FILLED);
        spot11.setWell(wellA1);
        spot11.setStatus(SpotStatus.PICKED);
        wellA2.setSpot(spot12);
        wellA2.setStatus(Well96Status.FILLED);
        spot12.setWell(wellA2);
        spot12.setStatus(SpotStatus.PICKED);
        wellB1.setSpot(spot21);
        wellB1.setStatus(Well96Status.FILLED);
        spot21.setWell(wellB1);
        spot21.setStatus(SpotStatus.PICKED);
        wellB2.setSpot(spot22);
        wellB2.setStatus(Well96Status.FILLED);
        spot22.setWell(wellB2);
        spot22.setStatus(SpotStatus.PICKED);

        //create 384 well plate
        IPlate384 plate384 = Lookup.getDefault().lookup(IPlate384Factory.class).createPlate384();
        plate384.setParent(project);
        project.add384Plate(plate384);
        plate384.setName("grosse Testplatte");
        plate384.setDescription("Mock Objekt zum Test der Datenstruktur");

        //provide processing information
        IWell384 well384_1 = plate384.getWell('F', 10);
        wellA1.add384Well(well384_1);
        wellA1.setStatus(Well96Status.PROCESSED);
        well384_1.setWell96(wellA1);
        well384_1.setStatus(Well384Status.FILLED);
        return project;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton plate384TestButton;
    private javax.swing.JButton plate96TestButton;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized TestModuleTopComponent getDefault() {
        if (instance == null) {
            instance = new TestModuleTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the TestModuleTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized TestModuleTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(TestModuleTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof TestModuleTopComponent) {
            return (TestModuleTopComponent) win;
        }
        Logger.getLogger(TestModuleTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }
}
