package de.unibielefeld.gi.kotte.laborprogramm.pathway.options;

import de.unibielefeld.gi.kotte.laborprogramm.pathway.utils.MetacycController;
import static de.unibielefeld.gi.kotte.laborprogramm.pathway.utils.MetacycController.defaultBiocycLocation;
import java.awt.GridLayout;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.filesystems.FileAlreadyLockedException;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;
import org.openide.util.NbPreferences;

final class PathwayManagerCachePanel extends JPanel implements DocumentListener {

    private final PathwayManagerCacheOptionsPanelController controller;

    PathwayManagerCachePanel(PathwayManagerCacheOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        cacheFileMaxAgeTextField.getDocument().addDocumentListener(this);
    }
    
    private boolean isUrl(String text) {
        try {
            URL u = new URL(text);
            return true;
        }catch(MalformedURLException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cacheDeleteLabel = new javax.swing.JLabel();
        deleteCacheButton = new javax.swing.JButton();
        oldCacheFilesCheckBox = new javax.swing.JCheckBox();
        cacheFileMaxAgeTextField = new javax.swing.JTextField();
        cacheAgeLabel = new javax.swing.JLabel();
        errorMessageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        serverLocationTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        org.openide.awt.Mnemonics.setLocalizedText(cacheDeleteLabel, org.openide.util.NbBundle.getMessage(PathwayManagerCachePanel.class, "PathwayManagerCachePanel.cacheDeleteLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(deleteCacheButton, org.openide.util.NbBundle.getMessage(PathwayManagerCachePanel.class, "PathwayManagerCachePanel.deleteCacheButton.text")); // NOI18N
        deleteCacheButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCacheButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(oldCacheFilesCheckBox, org.openide.util.NbBundle.getMessage(PathwayManagerCachePanel.class, "PathwayManagerCachePanel.oldCacheFilesCheckBox.text")); // NOI18N
        oldCacheFilesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldCacheFilesCheckBoxActionPerformed(evt);
            }
        });

        cacheFileMaxAgeTextField.setText(org.openide.util.NbBundle.getMessage(PathwayManagerCachePanel.class, "PathwayManagerCachePanel.cacheFileMaxAgeTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cacheAgeLabel, org.openide.util.NbBundle.getMessage(PathwayManagerCachePanel.class, "PathwayManagerCachePanel.cacheAgeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(errorMessageLabel, org.openide.util.NbBundle.getMessage(PathwayManagerCachePanel.class, "PathwayManagerCachePanel.errorMessageLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PathwayManagerCachePanel.class, "PathwayManagerCachePanel.jLabel1.text")); // NOI18N

        serverLocationTextField.setText(org.openide.util.NbBundle.getMessage(PathwayManagerCachePanel.class, "PathwayManagerCachePanel.serverLocationTextField.text")); // NOI18N
        serverLocationTextField.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent arg0) {
                return isUrl(serverLocationTextField.getText());
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PathwayManagerCachePanel.class, "PathwayManagerCachePanel.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oldCacheFilesCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cacheFileMaxAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cacheAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cacheDeleteLabel)
                    .addComponent(deleteCacheButton)
                    .addComponent(errorMessageLabel)
                    .addComponent(jLabel1)
                    .addComponent(serverLocationTextField)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cacheDeleteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteCacheButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldCacheFilesCheckBox)
                    .addComponent(cacheFileMaxAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cacheAgeLabel))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oldCacheFilesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldCacheFilesCheckBoxActionPerformed
        controller.changed();
    }//GEN-LAST:event_oldCacheFilesCheckBoxActionPerformed

    private void deleteCacheButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCacheButtonActionPerformed
        FileObject configFolder = FileUtil.getConfigFile("proteus");
        try {
            configFolder.delete();
        } catch (Exception ex) {
            JPanel panel = new JPanel();
            panel.setLayout(new GridLayout(2, 1));
            panel.add(new JLabel("Cache could not be deleted"));
            if (ex instanceof NullPointerException) {
                panel.add(new JLabel("Reason: There was no cache folder. Maybe it was already deleted."));
            } else if (ex instanceof FileAlreadyLockedException) {
                panel.add(new JLabel("Reason: The cache was locked. Maybe it is opened by another program."));
            } else { // instanceof IOException
                panel.add(new JLabel("Reason: The Filesystem did not allow a deletion of the cache."));
            }
            NotifyDescriptor nd = new NotifyDescriptor(panel, "Cache not deleted",
                    NotifyDescriptor.OK_CANCEL_OPTION, NotifyDescriptor.INFORMATION_MESSAGE,
                    null, NotifyDescriptor.YES_OPTION);
            DialogDisplayer.getDefault().notify(nd);
        }
    }//GEN-LAST:event_deleteCacheButtonActionPerformed

    void load() {
        oldCacheFilesCheckBox.setSelected(NbPreferences.forModule(MetacycController.class).getBoolean("check.cache.age", false));
        int i = NbPreferences.forModule(MetacycController.class).getInt("cache.time.to.live", 14);
        cacheFileMaxAgeTextField.setText(Integer.toString(i));
        serverLocationTextField.setText(NbPreferences.forModule(MetacycController.class).get("server.location", defaultBiocycLocation));
    }

    void store() {
        NbPreferences.forModule(MetacycController.class).putBoolean("check.cache.age", oldCacheFilesCheckBox.isSelected());
        NbPreferences.forModule(MetacycController.class).putInt("cache.time.to.live", Integer.parseInt(cacheFileMaxAgeTextField.getText()));
        NbPreferences.forModule(MetacycController.class).put(
                "server.location",
                serverLocationTextField.getText().isEmpty()?defaultBiocycLocation:serverLocationTextField.getText().trim()
        );
    }

    boolean valid() {
        int i;
        try {
            i = Integer.parseInt(cacheFileMaxAgeTextField.getText());
        } catch (NumberFormatException ex) {
            errorMessageLabel.setText("Amount of days to keep cache files is not a number!");
            return false;
        }
        if (i < 0) {
            errorMessageLabel.setText("Amount of days to keep cache files is negative!");
            return false;
        }
        errorMessageLabel.setText("");
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cacheAgeLabel;
    private javax.swing.JLabel cacheDeleteLabel;
    private javax.swing.JTextField cacheFileMaxAgeTextField;
    private javax.swing.JButton deleteCacheButton;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox oldCacheFilesCheckBox;
    private javax.swing.JTextField serverLocationTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
        updateTexts(e);
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        updateTexts(e);
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        updateTexts(e);
    }

    /**
     * Handles changes in the editable text fields
     */
    private void updateTexts(DocumentEvent e) {
//        if (e.getDocument() == cacheFileMaxAgeTextField.getDocument()) {
        controller.changed();
//        }
    }
}
