package de.unibielefeld.gi.kotte.laborprogramm.pathways.sbml;

import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import javax.swing.SwingUtilities;
import javax.xml.stream.XMLStreamException;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.util.Exceptions;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle.Messages;
import org.openide.util.RequestProcessor;
import org.openide.windows.TopComponent;
import org.sbml.jsbml.SBMLDocument;
import org.sbml.jsbml.xml.stax.SBMLReader;

/**
 * Top component which displays pathways represented as SBML documents.
 *
 * @author kotte
 */
@ConvertAsProperties(
    dtd = "-//de.unibielefeld.gi.kotte.laborprogramm.pathways.visualization//PathwayExplorer//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "PathwayExplorerTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "properties", openAtStartup = false)
@ActionID(category = "Window", id = "de.unibielefeld.gi.kotte.laborprogramm.pathways.visualization.PathwayExplorerTopComponent")
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_PathwayExplorerAction",
preferredID = "PathwayExplorerTopComponent")
@Messages({
    "CTL_PathwayExplorerAction=Pathway Explorer",
    "CTL_PathwayExplorerTopComponent=Pathway Explorer",
    "HINT_PathwayExplorerTopComponent=This is a Pathway Explorer Window"
})
public final class PathwayExplorerTopComponent extends TopComponent implements LookupListener {

    private boolean initialized = false;
    private PathwayController pathwayController;

    public PathwayExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_PathwayExplorerTopComponent());
        setToolTipText(Bundle.HINT_PathwayExplorerTopComponent());
    }

    public void openFile(final File file) {
        if (!initialized) {
            final ProgressHandle ph = ProgressHandleFactory.createHandle("Loading SBML File");
            RequestProcessor rp = new RequestProcessor(PathwayExplorerTopComponent.class);
            rp.post(new SBMLDocumentLoader(file, ph));
        }else {
            throw new IllegalStateException("Pathway Explorer was already initialized with an SBML File!");
        }
    }

    public void setPathwayController(PathwayController pathwayController) {
        this.pathwayController = pathwayController;
    }

    final class SBMLDocumentLoader implements Runnable {

        final File file;
        final ProgressHandle handle;

        public SBMLDocumentLoader(File file, ProgressHandle handle) {
            this.file = file;
            this.handle = handle;
        }

        @Override
        public void run() {
            try {
                handle.start();
                handle.progress("Loading SBML File " + file.getName());
                SBMLReader reader = new SBMLReader();
                SBMLDocument document = null;
                document = reader.readSBML(file);
                handle.progress("Creating Pathway Network Display");
                initPathwayDisplay(file, document, new PathwayDisplay(document, pathwayController));
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            } catch (XMLStreamException ex) {
                Exceptions.printStackTrace(ex);
            } finally {
                handle.finish();
            }
        }
    }

    private void initPathwayDisplay(final File file, final SBMLDocument document, final PathwayDisplay display) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                setDisplayName("Pathway Explorer of "+file.getName());
                setToolTipText("Model Id: "+document.getSBMLDocument().getModel().getId());
                open();
                add(display, BorderLayout.CENTER);
                requestActive();
                initialized = true;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
//        SBMLDocument document = Utilities.actionsGlobalContext().lookup(SBMLDocument.class);
//        if(document==null) {
//            throw new IllegalArgumentException("Instance of SBMLDocument must not be null!");
//        }
//        initPathwayDisplay(document);
    }

    @Override
    public void componentClosed() {
//        SBMLDocument doc = getLookup().lookup(SBMLDocument.class);
//        if (doc != null) {
//            Lookup.getDefault().lookup(IRegistryFactory.class).getDefault().closeTopComponentsFor(doc);
//        }
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void resultChanged(LookupEvent le) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
