package de.unibielefeld.gi.kotte.laborprogramm.pathway.wizard;

import de.unibielefeld.gi.kotte.laborprogramm.pathway.utils.CancellableRunnable;
import de.unibielefeld.gi.kotte.laborprogramm.pathway.utils.MetacycController;
import de.unibielefeld.gi.kotte.laborprogramm.pathway.utils.TypedListModel;
import de.unibielefeld.gi.omicsTools.biocyc.ptools.PGDB;
import de.unibielefeld.gi.omicsTools.biocyc.ptools.Strain;
import java.io.File;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.util.RequestProcessor;

public final class SBMLIMportVisualPanel1 extends JPanel {

    public static final String PROPERTY_PROJECT_NAME = "Pathway Project Name";
    public static final String PROPERTY_FILE = "SBML File";
    public static final String PROPERTY_ORGANISM = "PGDB";
    
    private TypedListModel<PGDB> organismListModel = new TypedListModel<PGDB>();
    private File file;
    private PGDB organism;

    /**
     * Creates new form SBMLIMportVisualPanel1
     */
    public SBMLIMportVisualPanel1() {
        initComponents();
        organismList.setModel(organismListModel);
        organismList.setCellRenderer(new PGDBCellRenderer());
        initOrganismList();
    }

    @Override
    public String getName() {
        return "Import SBML File";
    }
    
    public File getSBMLFile() {
        return file;
    }
    
    public PGDB getOrganism() {
        return (PGDB) organismList.getSelectedValue();
    }
    
    public String getProjectName() {
        return nameTextField.getText();
    }

    private void initOrganismList() {
        CancellableRunnable cr = new CancellableRunnable() {
            @Override
            public void body() {
                organismList.setVisible(false);
                this.handle.progress("Querying database");
                MetacycController mc = new MetacycController();
                List<PGDB> organisms = mc.getOrganisms();
                this.handle.progress("Sorting results");
                Collections.sort(organisms, new Comparator<PGDB>() {
                    @Override
                    public int compare(PGDB o1, PGDB o2) {
                        String name1 = PGDBCellRenderer.getSpeciesName(o1);
                        String name2 = PGDBCellRenderer.getSpeciesName(o2);
                        return name1.compareTo(name2);
                    }
                });
                this.handle.progress("Adding results to the list");
                organismListModel.setList(organisms);
                organismList.setVisible(true);
            }
        };

        final ProgressHandle ph = ProgressHandleFactory.createHandle("Fetching organism list", cr);
        cr.setHandle(ph);
        RequestProcessor rp = new RequestProcessor(SBMLIMportVisualPanel1.class);
        rp.post(cr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        organismLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organismList = new javax.swing.JList();
        separator = new javax.swing.JSeparator();
        fileLabel = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        fileButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(organismLabel, org.openide.util.NbBundle.getMessage(SBMLIMportVisualPanel1.class, "SBMLIMportVisualPanel1.organismLabel.text")); // NOI18N

        organismList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(organismList);

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        org.openide.awt.Mnemonics.setLocalizedText(fileLabel, org.openide.util.NbBundle.getMessage(SBMLIMportVisualPanel1.class, "SBMLIMportVisualPanel1.fileLabel.text")); // NOI18N

        fileTextField.setEditable(false);
        fileTextField.setText(org.openide.util.NbBundle.getMessage(SBMLIMportVisualPanel1.class, "SBMLIMportVisualPanel1.fileTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(fileButton, org.openide.util.NbBundle.getMessage(SBMLIMportVisualPanel1.class, "SBMLIMportVisualPanel1.fileButton.text")); // NOI18N
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(SBMLIMportVisualPanel1.class, "SBMLIMportVisualPanel1.nameLabel.text")); // NOI18N

        nameTextField.setText(org.openide.util.NbBundle.getMessage(SBMLIMportVisualPanel1.class, "SBMLIMportVisualPanel1.nameTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organismLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileLabel)
                    .addComponent(fileTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(organismLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        FileChooserBuilder fcb = new FileChooserBuilder(getClass());
        fcb.setTitle("Choose project directory");
        fcb.setDirectoriesOnly(true);
        JFileChooser jfc = fcb.createFileChooser();
        int status = jfc.showOpenDialog(this);
        if (status == JFileChooser.APPROVE_OPTION) {
            File oldFile = file;
            file = jfc.getSelectedFile();
            fileTextField.setText(file.getAbsolutePath());
            firePropertyChange(PROPERTY_FILE, oldFile, file);
        }
    }//GEN-LAST:event_fileButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel organismLabel;
    private javax.swing.JList organismList;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
